# Generated by Django 2.2.16 on 2020-09-26 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Choice Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Media from'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cheat',
            name='url_file',
            field=models.FileField(upload_to='cheats/', verbose_name='Cheat image (URL)'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='url_file',
            field=models.FileField(upload_to='dataset/', verbose_name='Student video (URL)'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='url_file',
            field=models.FileField(upload_to='emotions/', verbose_name='Cheat image (URL)'),
        ),
        migrations.AlterField(
            model_name='head',
            name='url_file',
            field=models.FileField(upload_to='headPose/', verbose_name='Cheat image (URL)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url_file',
            field=models.FileField(upload_to='multimedia/', verbose_name='schedule video or image (URL)'),
        ),
        migrations.AlterField(
            model_name='modelml',
            name='url_file',
            field=models.FileField(upload_to='models/', verbose_name='Model (URL)'),
        ),
    ]
